### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by phaalonso** [dxcore35/Suddha-theme#1]
Hi, I loved the theme but I think that to attract more people some part of the text needs to have better contrast with the background. Its practically illegible
![image](https://user-images.githubusercontent.com/26033899/101295845-cddd8600-37fe-11eb-953e-f1899c3f4aec.png)
![image](https://user-images.githubusercontent.com/26033899/101295863-e188ec80-37fe-11eb-9a37-6c7a32d037e9.png)
![image](https://user-images.githubusercontent.com/26033899/101295871-ecdc1800-37fe-11eb-9308-5b4128fa7810.png)
![image](https://user-images.githubusercontent.com/26033899/101295879-f1a0cc00-37fe-11eb-8614-4c017d9a6445.png)

**Comment by dxcore35** [comment]
Thank you!

The theme is not made with transparency plugin in mind. If you turn it off you will see different contrasts of the colors:

<img width="720" alt="Screenshot 2020-12-08 at 13 09 18" src="https://user-images.githubusercontent.com/7279156/101449490-46575a80-3957-11eb-8ae1-a7de4b89a644.png">

Please let me know!

**Comment by phaalonso** [comment]
I'm not using transparency plugin xD, maybe it can be the difference in the monitor that is causing this. I will try to test in another one

**Comment by dxcore35** [comment]
It cannot be monitor, we are making software screenshots not photo with phone :)
What is your OS?
