### ISSUE TITLE
Zoom on Photos feature is broken in v0.9.22 with Sliding Panes plugin

### ISSUE THREAD

**Issue by s-kyy** [dxcore35/Suddha-theme#2]
In the recent Obsidian update the zoom-in feature of this theme is broken when the sliding panes third party plugin is used. When I click and hold on the photo, instead of being contained in a specific pane, it expands to the entire obsidian software. 
![image](https://user-images.githubusercontent.com/19920083/102447120-54634600-3ffd-11eb-9f12-29be8f88bad7.png)

Without the sliding panes plugin, the photo zooms into the entire page. I'd rather the photo only zoom to fill in a specific pane. 
Would it be possible to have a css snippet that could do that, so people can have the option?

OS: Windows 10
Version 0.9.22

**Comment by dxcore35** [comment]
I have new v0.10 and I have opened 2 notes... and click on the photo...it look fine for me. Just one page is filled with fullscreen photo.

<img width="1071" alt="Screenshot 2020-12-17 at 13 32 12" src="https://user-images.githubusercontent.com/7279156/102454425-5fa18a80-406c-11eb-8ba4-623f451eba84.png">

**Comment by s-kyy** [comment]
Is line 1316 - 1382 the only css defining the image zoom? 
Could you see if the plugin affects your theme?


I'll message again after they release v0.10 outside of Insider to see if it is still affected, since I'm not an insider.

**Comment by dxcore35** [comment]
Does it work?

**Comment by s-kyy** [comment]
Yep it works now, thanks for the bump.
